Typography
Arbina001/Storybook_UI_components pull request #3
Opened 2023-12-19 17:41 UTC by Arbina001

### Headings typography
<img width="1272" alt="Screenshot 2023-12-19 at 11 04 02 PM" src="https://github.com/Arbina001/UI.adron/assets/153498385/3eeb8a79-1b3e-4a61-b4d8-90834557d499">

### Font Colors
<img width="1280" alt="Screenshot 2023-12-19 at 11 04 58 PM" src="https://github.com/Arbina001/UI.adron/assets/153498385/a094b927-d1cc-458a-8bfd-4eb7b4bf5b4f">

2023-12-27 06:17 UTC, tarakhant1297 requested changes

2023-12-27 06:17 UTC, tarakhant1297 commented on src/stories/Typography/typography.stories.js
> +    <Typography headingTag="h1" text="H1. Adorn Box heading" />
@Arbina001 give proper name to `headingTag ` follow antd Typography props name

2023-12-27 06:17 UTC, tarakhant1297 commented on src/stories/Typography/typography.style.js
> +    fontSize: '3rem',
@Arbina001 read from theme

2023-12-27 10:42 UTC, tarakhant1297 requested changes

2023-12-27 10:42 UTC, tarakhant1297 commented on src/stories/Typography/typography.stories.js
> +    <Typography htmlTag="h1" text="H1. Adorn Box heading" />
<Typography htmlTag="h1" >H1. Adorn Box heading</Typography>

2023-12-27 11:29 UTC, ankitadrixus08 approved these changes

2023-12-27 11:29 UTC, ankitadrixus08 commented on src/stories/Typography/typography.style.js
> +    lineHeight: '2.05rem',
line-height generally same as font or greater than this @Arbina001

2023-12-29 03:47 UTC, ankitadrixus08 approved these changes

2023-12-29 06:18 UTC, tarakhant1297 approved these changes

2023-12-29 13:36 UTC, merged