Alert
Arbina001/Storybook_UI_components pull request #4
Opened 2023-12-20 07:34 UTC by Arbina001

### Simple Alerts
<img width="1277" alt="Screenshot 2023-12-20 at 12 58 53 PM" src="https://github.com/Arbina001/UI.adron/assets/153498385/cfebdc42-d21e-4b4d-bf69-8a5b9a525664">
### Outline Alerts
<img width="1272" alt="Screenshot 2023-12-20 at 12 59 13 PM" src="https://github.com/Arbina001/UI.adron/assets/153498385/cd7d6168-1094-4c2e-b29c-0cb7c1fbf5b0">

2023-12-27 06:19 UTC, tarakhant1297 requested changes

2023-12-27 06:19 UTC, tarakhant1297 commented on src/stories/Alert/Alerts.stories.js
> +      disableHover
@Arbina001 why you need this `disableHover `

2023-12-27 06:19 UTC, tarakhant1297 commented on src/stories/Alert/Alerts.stories.js
> +      type="textcolorgray"
@Arbina001 give proper color name in theme .rename this `textcolorgray `in theme

2023-12-29 04:38 UTC, ankitadrixus08 commented on src/theme.js
> +  cardBorderColor: '#E49393',
dont need to add color after color name @Arbina001 

also from 13-16 change name of that color

2023-12-29 06:19 UTC, tarakhant1297 approved these changes

2023-12-29 06:47 UTC, ankitadrixus08 approved these changes

2023-12-29 13:59 UTC, merged