Avatar
Arbina001/Storybook_UI_components pull request #5
Opened 2023-12-20 13:36 UTC by Arbina001

### Square Avatar
<img width="1275" alt="Screenshot 2023-12-20 at 6 58 34 PM" src="https://github.com/Arbina001/UI.adron/assets/153498385/f77325c3-8ecc-41f2-94e0-27ded0361964">

### Circle Avatar
<img width="1280" alt="Screenshot 2023-12-20 at 6 59 00 PM" src="https://github.com/Arbina001/UI.adron/assets/153498385/8c5f121e-4351-4957-9972-dbec6a3fbb67">

2023-12-27 06:22 UTC, tarakhant1297 requested changes
follow props name as antd `https://ant.design/components/avatar`

2023-12-27 06:22 UTC, tarakhant1297 commented on src/stories/Avatar.Styled.js
> +export const AvatarContainer = styled.div`
@Arbina001 add prefix 'styled' in styled component `StyledAvatarContainer `

2023-12-27 06:22 UTC, tarakhant1297 commented on src/stories/Avatar.js
> +  return <Mainphoto src={url} Size={Size} shape={variant} />;
@Arbina001 give proper name to `Mainphoto `

2023-12-29 04:38 UTC, ankitadrixus08 approved these changes

2023-12-29 14:14 UTC, merged